title: Le blog d'Arthur Garreau
author: cqncpdp
email: arthurgarreau.web@gmail.com
description: > #multiline
  Hi I am Arthur Garreau ðŸ‡«ðŸ‡·, I hope you enjoy my blog and will find something useful.
  This website was created in 2017 by me using Jekyll and Github Pages,
  and you can CC-BY-NC-SA everything.

twitter_username: GarreauArthur
github_username: GarreauArthur
about: about
# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
disqus:
  shortname: cqncpdp
url: http://arthur.garreau.xyz
